// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: masterapi.proto

package masterapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMapTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapTaskRequest) Reset() {
	*x = GetMapTaskRequest{}
	mi := &file_masterapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapTaskRequest) ProtoMessage() {}

func (x *GetMapTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_masterapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapTaskRequest.ProtoReflect.Descriptor instead.
func (*GetMapTaskRequest) Descriptor() ([]byte, []int) {
	return file_masterapi_proto_rawDescGZIP(), []int{0}
}

func (x *GetMapTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type GetMapTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskDataPath  string                 `protobuf:"bytes,3,opt,name=task_data_path,json=taskDataPath,proto3" json:"task_data_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMapTaskResponse) Reset() {
	*x = GetMapTaskResponse{}
	mi := &file_masterapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMapTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMapTaskResponse) ProtoMessage() {}

func (x *GetMapTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_masterapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMapTaskResponse.ProtoReflect.Descriptor instead.
func (*GetMapTaskResponse) Descriptor() ([]byte, []int) {
	return file_masterapi_proto_rawDescGZIP(), []int{1}
}

func (x *GetMapTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetMapTaskResponse) GetTaskDataPath() string {
	if x != nil {
		return x.TaskDataPath
	}
	return ""
}

type SubmitMapTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	WorkerId       string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	TaskId         string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ResultDataPath string                 `protobuf:"bytes,4,opt,name=result_data_path,json=resultDataPath,proto3" json:"result_data_path,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubmitMapTaskRequest) Reset() {
	*x = SubmitMapTaskRequest{}
	mi := &file_masterapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMapTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMapTaskRequest) ProtoMessage() {}

func (x *SubmitMapTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_masterapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMapTaskRequest.ProtoReflect.Descriptor instead.
func (*SubmitMapTaskRequest) Descriptor() ([]byte, []int) {
	return file_masterapi_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitMapTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *SubmitMapTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SubmitMapTaskRequest) GetResultDataPath() string {
	if x != nil {
		return x.ResultDataPath
	}
	return ""
}

type SubmitMapTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitMapTaskResponse) Reset() {
	*x = SubmitMapTaskResponse{}
	mi := &file_masterapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitMapTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitMapTaskResponse) ProtoMessage() {}

func (x *SubmitMapTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_masterapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitMapTaskResponse.ProtoReflect.Descriptor instead.
func (*SubmitMapTaskResponse) Descriptor() ([]byte, []int) {
	return file_masterapi_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitMapTaskResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SubmitMapTaskResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	WorkerAddress string                 `protobuf:"bytes,2,opt,name=worker_address,json=workerAddress,proto3" json:"worker_address,omitempty"`
	WorkerPort    string                 `protobuf:"bytes,3,opt,name=worker_port,json=workerPort,proto3" json:"worker_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_masterapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_masterapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_masterapi_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterWorkerRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *RegisterWorkerRequest) GetWorkerAddress() string {
	if x != nil {
		return x.WorkerAddress
	}
	return ""
}

func (x *RegisterWorkerRequest) GetWorkerPort() string {
	if x != nil {
		return x.WorkerPort
	}
	return ""
}

type RegisterWorkerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_masterapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_masterapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_masterapi_proto_rawDescGZIP(), []int{5}
}

func (x *RegisterWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterWorkerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_masterapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_masterapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_masterapi_proto_rawDescGZIP(), []int{6}
}

func (x *HeartbeatRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_masterapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_masterapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_masterapi_proto_rawDescGZIP(), []int{7}
}

func (x *HeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HeartbeatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_masterapi_proto protoreflect.FileDescriptor

const file_masterapi_proto_rawDesc = "" +
	"\n" +
	"\x0fmasterapi.proto\"0\n" +
	"\x11GetMapTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"S\n" +
	"\x12GetMapTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12$\n" +
	"\x0etask_data_path\x18\x03 \x01(\tR\ftaskDataPath\"v\n" +
	"\x14SubmitMapTaskRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12(\n" +
	"\x10result_data_path\x18\x04 \x01(\tR\x0eresultDataPath\"K\n" +
	"\x15SubmitMapTaskResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"|\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12%\n" +
	"\x0eworker_address\x18\x02 \x01(\tR\rworkerAddress\x12\x1f\n" +
	"\vworker_port\x18\x03 \x01(\tR\n" +
	"workerPort\"L\n" +
	"\x16RegisterWorkerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"G\n" +
	"\x11HeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xf9\x01\n" +
	"\tMasterApi\x125\n" +
	"\n" +
	"GetMapTask\x12\x12.GetMapTaskRequest\x1a\x13.GetMapTaskResponse\x12>\n" +
	"\rSubmitMapTask\x12\x15.SubmitMapTaskRequest\x1a\x16.SubmitMapTaskResponse\x12A\n" +
	"\x0eRegisterWorker\x12\x16.RegisterWorkerRequest\x1a\x17.RegisterWorkerResponse\x122\n" +
	"\tHeartbeat\x12\x11.HeartbeatRequest\x1a\x12.HeartbeatResponseB\x0eZ\f./;masterapib\x06proto3"

var (
	file_masterapi_proto_rawDescOnce sync.Once
	file_masterapi_proto_rawDescData []byte
)

func file_masterapi_proto_rawDescGZIP() []byte {
	file_masterapi_proto_rawDescOnce.Do(func() {
		file_masterapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_masterapi_proto_rawDesc), len(file_masterapi_proto_rawDesc)))
	})
	return file_masterapi_proto_rawDescData
}

var file_masterapi_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_masterapi_proto_goTypes = []any{
	(*GetMapTaskRequest)(nil),      // 0: GetMapTaskRequest
	(*GetMapTaskResponse)(nil),     // 1: GetMapTaskResponse
	(*SubmitMapTaskRequest)(nil),   // 2: SubmitMapTaskRequest
	(*SubmitMapTaskResponse)(nil),  // 3: SubmitMapTaskResponse
	(*RegisterWorkerRequest)(nil),  // 4: RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil), // 5: RegisterWorkerResponse
	(*HeartbeatRequest)(nil),       // 6: HeartbeatRequest
	(*HeartbeatResponse)(nil),      // 7: HeartbeatResponse
}
var file_masterapi_proto_depIdxs = []int32{
	0, // 0: MasterApi.GetMapTask:input_type -> GetMapTaskRequest
	2, // 1: MasterApi.SubmitMapTask:input_type -> SubmitMapTaskRequest
	4, // 2: MasterApi.RegisterWorker:input_type -> RegisterWorkerRequest
	6, // 3: MasterApi.Heartbeat:input_type -> HeartbeatRequest
	1, // 4: MasterApi.GetMapTask:output_type -> GetMapTaskResponse
	3, // 5: MasterApi.SubmitMapTask:output_type -> SubmitMapTaskResponse
	5, // 6: MasterApi.RegisterWorker:output_type -> RegisterWorkerResponse
	7, // 7: MasterApi.Heartbeat:output_type -> HeartbeatResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_masterapi_proto_init() }
func file_masterapi_proto_init() {
	if File_masterapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_masterapi_proto_rawDesc), len(file_masterapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_masterapi_proto_goTypes,
		DependencyIndexes: file_masterapi_proto_depIdxs,
		MessageInfos:      file_masterapi_proto_msgTypes,
	}.Build()
	File_masterapi_proto = out.File
	file_masterapi_proto_goTypes = nil
	file_masterapi_proto_depIdxs = nil
}
